# Generated by Django 6.0.6 on 2026-06-11 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_stock_minimo_alter_producto_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código/SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('metro', 'Metro')], default='unidad', max_length=20),
        ),
    ]
