# Generated by Django 6.0.6 on 2026-06-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_producto_ubicacion_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion_categoria',
            field=models.CharField(blank=True, choices=[('bodega', 'Bodega'), ('estanteria', 'Estanteria'), ('mostrador', 'Mostrador'), ('oficina', 'Oficina'), ('frio', 'Cadena de frio'), ('externo', 'Externo')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=80)),
                ('objeto', models.CharField(blank=True, max_length=120)),
                ('detalle', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_categoria_origen', models.CharField(blank=True, choices=[('bodega', 'Bodega'), ('estanteria', 'Estanteria'), ('mostrador', 'Mostrador'), ('oficina', 'Oficina'), ('frio', 'Cadena de frio'), ('externo', 'Externo')], default='', max_length=20)),
                ('ubicacion_origen', models.CharField(blank=True, default='', max_length=120)),
                ('ubicacion_categoria_destino', models.CharField(blank=True, choices=[('bodega', 'Bodega'), ('estanteria', 'Estanteria'), ('mostrador', 'Mostrador'), ('oficina', 'Oficina'), ('frio', 'Cadena de frio'), ('externo', 'Externo')], default='', max_length=20)),
                ('ubicacion_destino', models.CharField(blank=True, default='', max_length=120)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_ubicacion', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
